# Pipeline DVC pour le projet MLOps

stages:
  prepare:
    cmd: poetry run python -m src.data.prepare
    deps:
      - src/data/prepare.py
      - src/config.py
      - params.yaml
    outs:
      - data/raw/iris.csv
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - data.test_size
      - data.random_state

  train:
    cmd: poetry run python -m src.training.train
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/training/train.py
      - src/evaluation/evaluate.py
      - src/config.py
      - params.yaml
    outs:
      - models/metadata.json
    metrics:
      - models/metrics.json
    params:
      - train.n_estimators
      - train.max_depth
      - data.random_state
      - data.test_size

