# Paramètres du pipeline DVC
# Utilisé pour configurer les hyperparamètres et les paramètres de données

data:
  test_size: 0.2
  random_state: 42

train:
  n_estimators: 100
  max_depth: null  # null = illimitée
  random_state: 42
  test_size: 0.2

